# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0006_update_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'get_latest_by': 'order'},
        ),
        migrations.AlterModelOptions(
            name='usernamechange',
            options={'get_latest_by': 'changed_on'},
        ),
    ]
