# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0007_auto_20170213_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_uid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fb_user',
            field=models.BooleanField(default=True),
        ),
    ]
