# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0009_auto_20170213_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fb_uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
